### ISSUE TITLE
v2.1: Typo in Login Dialog: Resquest Security Code

### ISSUE THREAD

**Issue by JashanChittesh** [modio/UnityPlugin#15]
Interestingly, that typo isn't there in v2.0.

Repro steps: 
1. Open ExampleScene
2. Enter Play Mode
3. Click on button on bottom right: mods powered by mod.io
4. Enter your email-address

As soon as the email validation passes (i.e. you entered a valid email address), the button changes the text from "Authenticate" to "Re**_s_**quest Security Code". That first "s" should not be there.

This should be trivial to fix but as its in the prefab, probably not something where a pull request would make sense. See attached screenshot for where this is:

<img width="426" alt="Capture_TypoResquest" src="https://user-images.githubusercontent.com/986684/64023231-215f1f80-cb38-11e9-8544-aafc274238e1.PNG">

**Comment by Melodatron** [comment]
Fixed for next release.
