### ISSUE TITLE
v2.1: Clicking "mods powered by mods.io" button "gets stuck"

### ISSUE THREAD

**Issue by JashanChittesh** [modio/UnityPlugin#16]
When clicking the button "mods powered by mods.io" after previously logging in, you can "View Profile" and "Log Out". Those two things work - but the only way to exit that state is to log out. In other words, you cannot get "back to normal", e.g. by clicking anywhere on the UI, or viewing the profile.

"Log Out" works as expected (it logs out and restores the "normal state"). But once that button was clicked, you have to log out to get out of that state. You cannot "View profile" or click anywhere else to return to normal.

**Comment by intenscia** [comment]
Hey @JashanChittesh amazing feedback - i've let our Unity developer @Melodatron know so he can start working through these.

Keep it coming! Oh and we have Oculus login support coming in a patch soon to the API (will take a little longer to get into the Unity build)

**Comment by Melodatron** [comment]
Fixed for next release.
