### ISSUE TITLE
v2.1: Mod Details don't load, exception is thrown

### ISSUE THREAD

**Issue by JashanChittesh** [modio/UnityPlugin#17]
When clicking on a Mod, the details pane shows up - but the data is not loaded. There are also two exceptions thrown the first time, and one exception thrown when closing / reopening the details:

On first click:

> NullReferenceException: Object reference not set to an instance of an object
> ModIO.UI.ModfileContainer.DisplayModfiles (System.Collections.Generic.IList`1[T] modfiles) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/DisplayComponents/ModfileContainer.cs:138)
> ModIO.UI.ModfileContainer.OnEnable () (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/DisplayComponents/ModfileContainer.cs:99)
> UnityEngine.GameObject:SetActive(Boolean)
> ModIO.UI.ViewManager:InspectMod(Int32) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/ViewManager.cs:80)
> ModIO.UI.ModView:InspectMod() (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/ModView.cs:119)
> UnityEngine.EventSystems.EventSystem:Update()
> 
> NullReferenceException: Object reference not set to an instance of an object
> ModIO.UI.ModfileContainer.DisplayModfiles (System.Collections.Generic.IList`1[T] modfiles) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/DisplayComponents/ModfileContainer.cs:138)
> ModIO.UI.ModReleaseHistoryDisplay.RequestReleaseHistory (System.Int32 modId) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/DisplayComponents/ModReleaseHistoryDisplay.cs:98)
> ModIO.UI.ModReleaseHistoryDisplay.RequestReleaseHistory (ModIO.ModProfile modProfile) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/DisplayComponents/ModReleaseHistoryDisplay.cs:87)
> ModIO.UI.ModReleaseHistoryDisplay.SetModView (ModIO.UI.ModView view) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/DisplayComponents/ModReleaseHistoryDisplay.cs:68)
> ModIO.UI.ModView.Start () (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/ModView.cs:109)

On second click:

> NullReferenceException: Object reference not set to an instance of an object
> ModIO.UI.UIUtilities.SetInstanceCount[T] (UnityEngine.Transform container, T template, System.String instanceName, System.Int32 instanceCount, T[]& instanceArray, System.Boolean reactivateAll) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/Utility/UIUtilities.cs:217)
> ModIO.UI.ModfileContainer.DisplayModfiles (System.Collections.Generic.IList`1[T] modfiles) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/DisplayComponents/ModfileContainer.cs:127)
> ModIO.UI.ModReleaseHistoryDisplay+<>c__DisplayClass9_0.<RequestReleaseHistory>b__0 (ModIO.RequestPage`1[T] r) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/UI/DisplayComponents/ModReleaseHistoryDisplay.cs:122)
> ModIO.APIClient+<>c__DisplayClass16_0`1[T].<SendRequest>b__0 () (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/APIClient.cs:482)
> ModIO.APIClient+<>c__DisplayClass15_0.<SendRequest>b__0 (UnityEngine.AsyncOperation operation) (at C:/GameDev/GitHub/modio-UnityPlugin-AsPackage/src/APIClient.cs:450)
> UnityEngine.AsyncOperation.InvokeCompletionEvent () (at C:/buildslave/unity/build/Runtime/Export/Scripting/AsyncOperation.cs:21)

<img width="406" alt="Capture_DetailsNotLoaded" src="https://user-images.githubusercontent.com/986684/64023595-f1644c00-cb38-11e9-9a32-f54565a0006c.PNG">

**Comment by Melodatron** [comment]
Fixed for next release.
