### ISSUE TITLE
PluginSettings does not support overrides of game ID / API Key during builds

### ISSUE THREAD

**Issue by JashanChittesh** [modio/UnityPlugin#21]
We have one project for multiple games, so have a build process that overrides game specific IDs like the Steam and Oculus game IDs. The mod.io UnityPlugin is the first time this requires a change in the plugin-code: With PluginSettings being just a wrapper, and Data being a struct, with static read-only access, we cannot override gameId and gameAPIKey.

My workaround, for now, is adding a property:

```
public Data InstanceData
{
    get => m_data;
    set => m_data = value;
}
```

Then, I load PluginSettings via Resources.Load..., get InstanceData, override gameId and gameAPIKey, and store the changed struct back into InstanceData. So this requires quite a bit of boilerplate code:

```
ModIO.PluginSettings modioPluginSettings = Resources.Load<ModIO.PluginSettings>(ModIO.PluginSettings.FILE_PATH);
            
ModIO.PluginSettings.Data modIOData = modioPluginSettings.InstanceData; 
modIOData.gameId = modioGameId;
modIOData.gameAPIKey = modioGameAPIKey;
modioPluginSettings.InstanceData = modIOData;
            
EditorUtility.SetDirty(modioPluginSettings);
            
AssetDatabase.SaveAssets();
```

This would be much smoother, if PluginSettings was a singleton, and PluginSettings.Data was a class instead of struct. For comparison, here is how we override the Oculus platform settings (PlatformSettings.Instance handles the loading for us, so we don't have to worry about where this is stored):

```
Oculus.Platform.PlatformSettings oculusPlatformSettings = Oculus.Platform.PlatformSettings.Instance;
Oculus.Platform.PlatformSettings.AppID = oculusApplicationId;
EditorUtility.SetDirty(oculusPlatformSettings);
```

**Comment by Melodatron** [comment]
Fixed for next release
