### ISSUE TITLE
ModTeamMemberAccessLevel.Statistics same as Manager permission?

### ISSUE THREAD

**Issue by KristianMischke** [modio/UnityPlugin#43]
The file `Runtime/Enums/ModTeamMemberAccessLevel.cs` contains these definitions for TeamMember Access:

```cs
public enum ModTeamMemberAccessLevel
{
    Moderator = 1, // can moderate content submitted
    Statistics = 4, // moderator access, including read only access to view reports
    Administrator = 8, // full access, including editing the profile and team
}
```

But the "Edit Team" screen on the modio website lists these permissions:

> Moderator - can moderate comments and content attached
> Manager - moderator access, including uploading builds and editing settings except supply and team members
> Administrator - full access, including editing the supply and team

Is `ModTeamMemberAccess.Statistics` the same as the "Manager" permission or not? I'm trying to filter mods based on who can upload new builds.

**Comment by modio-jackson** [comment]
Thanks for bringing this to my attention. The definitions may have changed at some point since the initial implementation.
Yes, `Statistics` is equivalent to `Manager`.
I'll create a pull request shortly to update this.

**Comment by modio-jackson** [comment]
Updated here:
https://github.com/modio/UnityPlugin/pull/44
