### ISSUE TITLE
BUG: åäö characters creating a undesired filename on modfile upload.

### ISSUE THREAD

**Issue by Melodatron** [modio/UnityPlugin#9]

**Comment by Melodatron** [comment]
https://cdn.discordapp.com/attachments/563195660124553216/565123671241523200/FileName.png

**Comment by Melodatron** [comment]
https://cdn.discordapp.com/attachments/563195660124553216/565123671241523200/FileName.png

**Comment by intenscia** [comment]
Fixed on our end
